apiVersion: v1
kind: Service
metadata:
    name: ajd-web
spec:
    selector:
        app: ajd-web
        tier: frontend
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajd-web
spec:
  selector:
    matchLabels:
      app: ajd-web
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: ajd-web
        tier: frontend
        track: stable
    spec:
      containers:
        - name: ajd-web
          image: "gcr.io/data-science-radar/ajd-web:v5"
          ports:
            - name: http
              containerPort: 80
